CREATE TABLE fin_prop_list (
    id BIGINT PRIMARY KEY,
    name TEXT,
    sec_name TEXT,
    is_bank BOOLEAN,
    is_user BOOLEAN,
    is_state BOOLEAN
);

CREATE TABLE fin_state_list (
    id BIGINT PRIMARY KEY,
    state TEXT,
    income_tax REAL,
    housing INTEGER,
    constraint fin_state_list_unique_key unique (state)
);

CREATE TABLE fin_bank_list (
    id UUID PRIMARY KEY,
    name TEXT,
    interest_rate DOUBLE PRECISION,
    process_fee DOUBLE PRECISION,
    flat_fee BOOLEAN,
    interest_accum_rate SMALLINT,
    last_dist DATE
);

CREATE TABLE fin_user_list (
    id UUID PRIMARY KEY,
    fname TEXT,
    lname TEXT,
    state TEXT,
    bank UUID,
    checking DOUBLE PRECISION,
    saving DOUBLE PRECISION,
    income DOUBLE PRECISION,
    pay_period SMALLINT,
    works_monday BOOLEAN,
    works_tuesday BOOLEAN,
    works_wednesday BOOLEAN,
    works_thursday BOOLEAN,
    works_friday BOOLEAN,
    shift_length SMALLINT,
    accum_hours INTEGER,
    CONSTRAINT fin_user_list_bank_fkey FOREIGN KEY (bank) REFERENCES fin_bank_list (id),
    CONSTRAINT fin_user_list_state_fkey FOREIGN KEY (state) REFERENCES fin_state_list (state)
);

CREATE TABLE fin_transac_list (
    id BIGINT PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE,
    sender UUID,
    receiver UUID,
    amount DOUBLE PRECISION,
    note TEXT,
    CONSTRAINT fin_transac_list_receiver_fkey FOREIGN KEY (receiver) REFERENCES fin_user_list (id),
    CONSTRAINT fin_transac_list_receiver_fkey1 FOREIGN KEY (receiver) REFERENCES fin_bank_list (id),
    CONSTRAINT fin_transac_list_sender_fkey FOREIGN KEY (sender) REFERENCES fin_bank_list (id),
    CONSTRAINT fin_transac_list_sender_fkey1 FOREIGN KEY (sender) REFERENCES fin_user_list (id)
);


INSERT INTO "public"."fin_prop_list" ("id", "name", "sec_name", "is_bank", "is_user", "is_state") VALUES
(1, 'AL', NULL, false, false, true),
(2, 'AK', NULL, false, false, true),
(3, 'AZ', NULL, false, false, true),
(4, 'AR', NULL, false, false, true),
(5, 'CA', NULL, false, false, true),
(6, 'CO', NULL, false, false, true),
(7, 'CT', NULL, false, false, true),
(8, 'DE', NULL, false, false, true),
(9, 'FL', NULL, false, false, true),
(10, 'GA', NULL, false, false, true),
(11, 'HI', NULL, false, false, true),
(12, 'ID', NULL, false, false, true),
(13, 'IL', NULL, false, false, true),
(14, 'IN', NULL, false, false, true),
(15, 'IA', NULL, false, false, true),
(16, 'KS', NULL, false, false, true),
(17, 'KY', NULL, false, false, true),
(18, 'LA', NULL, false, false, true),
(19, 'ME', NULL, false, false, true),
(20, 'MD', NULL, false, false, true),
(21, 'MA', NULL, false, false, true),
(22, 'MI', NULL, false, false, true),
(23, 'MN', NULL, false, false, true),
(24, 'MS', NULL, false, false, true),
(25, 'MO', NULL, false, false, true),
(26, 'MT', NULL, false, false, true),
(27, 'NE', NULL, false, false, true),
(28, 'NV', NULL, false, false, true),
(29, 'NH', NULL, false, false, true),
(30, 'NJ', NULL, false, false, true),
(31, 'NM', NULL, false, false, true),
(32, 'NY', NULL, false, false, true),
(33, 'NC', NULL, false, false, true),
(34, 'ND', NULL, false, false, true),
(35, 'OH', NULL, false, false, true),
(36, 'OK', NULL, false, false, true),
(37, 'OR', NULL, false, false, true),
(38, 'PA', NULL, false, false, true),
(39, 'RI', NULL, false, false, true),
(40, 'SC', NULL, false, false, true),
(41, 'SD', NULL, false, false, true),
(42, 'TN', NULL, false, false, true),
(43, 'TX', NULL, false, false, true),
(44, 'UT', NULL, false, false, true),
(45, 'VT', NULL, false, false, true),
(46, 'VA', NULL, false, false, true),
(47, 'WA', NULL, false, false, true),
(48, 'WV', NULL, false, false, true),
(49, 'WI', NULL, false, false, true),
(50, 'WY', NULL, false, false, true),
(51, 'Suncrest', NULL, true, false, false),
(52, 'Choice', NULL, true, false, false),
(53, 'Miner', NULL, true, false, false),
(54, 'Hill', NULL, true, false, false),
(55, 'Seagull', NULL, true, false, false),
(56, 'Oak', NULL, true, false, false),
(57, 'Tile', NULL, true, false, false),
(58, 'Avenue', NULL, true, false, false),
(59, 'Sunstorm', NULL, true, false, false),
(60, 'Crowsend', NULL, true, false, false),
(61, 'Sarah', NULL, false, true, false),
(62, 'James', NULL, false, true, false),
(63, 'Emily', NULL, false, true, false),
(64, 'Michael', NULL, false, true, false),
(65, 'Jessica', NULL, false, true, false),
(66, 'David', NULL, false, true, false),
(67, 'Sophia', NULL, false, true, false),
(68, 'John', NULL, false, true, false),
(69, 'Olivia', NULL, false, true, false),
(70, 'Daniel', NULL, false, true, false),
(71, 'Emma', NULL, false, true, false),
(72, 'Matthew', NULL, false, true, false),
(73, 'Ava', NULL, false, true, false),
(74, 'Andrew', NULL, false, true, false),
(75, 'Isabella', NULL, false, true, false),
(76, 'Christopher', NULL, false, true, false),
(77, 'Mia', NULL, false, true, false),
(78, 'Joseph', NULL, false, true, false),
(79, 'Amelia', NULL, false, true, false),
(80, 'Benjamin', NULL, false, true, false),
(81, NULL, 'Jones', false, true, false),
(82, NULL, 'Smith', false, true, false),
(83, NULL, 'Taylor', false, true, false),
(84, NULL, 'Brown', false, true, false),
(85, NULL, 'Johnson', false, true, false),
(86, NULL, 'Williams', false, true, false),
(87, NULL, 'Miller', false, true, false),
(88, NULL, 'Davis', false, true, false),
(89, NULL, 'Garcia', false, true, false),
(90, NULL, 'Rodriguez', false, true, false),
(91, NULL, 'Martinez', false, true, false),
(92, NULL, 'Hernandez', false, true, false),
(93, NULL, 'Lopez', false, true, false),
(94, NULL, 'Gonzalez', false, true, false),
(95, NULL, 'Perez', false, true, false),
(96, NULL, 'Wilson', false, true, false),
(97, NULL, 'Anderson', false, true, false),
(98, NULL, 'Thomas', false, true, false),
(99, NULL, 'Moore', false, true, false),
(100, NULL, 'Jackson', false, true, false);
ALTER TABLE fin_prop_list ENABLE ROW LEVEL SECURITY;

ALTER TABLE fin_bank_list ENABLE ROW LEVEL SECURITY;

ALTER TABLE fin_state_list ENABLE ROW LEVEL SECURITY;

ALTER TABLE fin_user_list ENABLE ROW LEVEL SECURITY;

ALTER TABLE fin_transac_list ENABLE ROW LEVEL SECURITY;
